title = "Sihan Yu - Personal Website"

[params.author]
name = "Sihan Yu"
image = "img/author.jpg"
headline = "Information & Computer Engineering Student | Software Engineer (starting 2026)"
# bio = "This is the bio"
links = [
  { linkedin = "https://www.linkedin.com/in/sihan-yu-110903238/" },
  { github = "https://github.com/sihanyu03/" }
]